[General]
Component=Hammurabi
Description=Hammurabi
DefaultDirectory=Programme
CabCount=4
Cab0=Hammurabi.Mips 4000 (1K) v2.10.cab
Cab1=Hammurabi.SH 4 (4K) v2.10.cab
Cab2=Hammurabi.Arm 1100 (4K) v2.10.cab
Cab3=Hammurabi.SH 3 (1K) v2.10.cab
