[General]
Component=FinancialCalc
Description=Financial Calculator
DefaultDirectory=Programme
CabCount=4
Cab0=FinancialCalc.Mips 4000 (1K) v2.10.cab
Cab1=FinancialCalc.SH 4 (4K) v2.10.cab
Cab2=FinancialCalc.Arm 1100 (4K) v2.10.cab
Cab3=FinancialCalc.SH 3 (1K) v2.10.cab
