[General]
Component=SimplyDB
Description=Database app
DefaultDirectory=Programme
CabCount=4
Cab0=SimplyDB.Mips 4000 (1K) v2.10.cab
Cab1=SimplyDB.SH 4 (4K) v2.10.cab
Cab2=SimplyDB.Arm 1100 (4K) v2.10.cab
Cab3=SimplyDB.SH 3 (1K) v2.10.cab
