[General]
Component=MachineCode
Description=MachineCode
DefaultDirectory=Programme
CabCount=4
Cab0=MachineCode.Mips 4000 (1K) v2.10.cab
Cab1=MachineCode.SH 4 (4K) v2.10.cab
Cab2=MachineCode.Arm 1100 (4K) v2.10.cab
Cab3=MachineCode.SH 3 (1K) v2.10.cab
