[General]
Component=LEDClock
Description=Clock
DefaultDirectory=Programme
CabCount=4
Cab0=LEDClock.Mips 4000 (1K) v2.10.cab
Cab1=LEDClock.SH 4 (4K) v2.10.cab
Cab2=LEDClock.Arm 1100 (4K) v2.10.cab
Cab3=LEDClock.SH 3 (1K) v2.10.cab
