[General]
Component=TravelDiary
Description=Travel Diary
DefaultDirectory=Programme
CabCount=4
Cab0=TravelDiary.Mips 4000 (1K) v2.10.cab
Cab1=TravelDiary.SH 4 (4K) v2.10.cab
Cab2=TravelDiary.Arm 1100 (4K) v2.10.cab
Cab3=TravelDiary.SH 3 (1K) v2.10.cab
