[General]
Component=Yahtzee
DefaultDirectory=Programme
CabCount=4
Cab0=Yahtzee.Mips 4000 (1K) v2.10.cab
Cab1=Yahtzee.SH 4 (4K) v2.10.cab
Cab2=Yahtzee.Arm 1100 (4K) v2.10.cab
Description=Yahtzee
Cab3=Yahtzee.SH 3 (1K) v2.10.cab
