[General]
Component=MemoryCE
Description=SuperMemo
DefaultDirectory=Programme
CabCount=4
Cab0=MemoryCE.Mips 4000 (1K) v2.10.cab
Cab1=MemoryCE.SH 4 (4K) v2.10.cab
Cab2=MemoryCE.Arm 1100 (4K) v2.10.cab
Cab3=MemoryCE.SH 3 (1K) v2.10.cab
