[General]
Component=CEBills
Description=CEBills
DefaultDirectory=Programme
CabCount=4
Cab0=CEBills.Mips 4000 (1K) v2.10.cab
Cab1=CEBills.SH 4 (4K) v2.10.cab
Cab2=CEBills.Arm 1100 (4K) v2.10.cab
Cab3=CEBills.SH 3 (1K) v2.10.cab
