[General]
Component=SuperClipboard
Description=Infinite clipboard
DefaultDirectory=Programme
CabCount=4
Cab0=SuperClipboard.Mips 4000 (1K) v2.10.cab
Cab1=SuperClipboard.SH 4 (4K) v2.10.cab
Cab2=SuperClipboard.Arm 1100 (4K) v2.10.cab
Cab3=SuperClipboard.SH 3 (1K) v2.10.cab
