[General]
Component=FWert
Description=Fair value calculator
DefaultDirectory=Programme
CabCount=4
Cab0=FWert.Mips 4000 (1K) v2.10.cab
Cab1=FWert.SH 4 (4K) v2.10.cab
Cab2=FWert.Arm 1100 (4K) v2.10.cab
Cab3=FWert.SH 3 (1K) v2.10.cab
